version: "3.9"

services:
#  livekit:
#    image: livekit/livekit-server:latest
#    container_name: livekit
#    command: --dev --config /etc/livekit/config.yml
##    에러 로그 : Incorrect Usage: flag provided but not defined: -metrics-listen
##    처리 : 기본적으로 7881 포트에서 /metrics 엔드포인트 제공
##    command: >
##      --dev
##      --bind 0.0.0.0
##      --port 7880
##      --udp-port 7882
##      --metrics-listen 0.0.0.0:7881
#    volumes:
#      - ./livekit-config.yml:/etc/livekit/config.yml
#    ports:
#      - "7880:7880"        # API/Signal (HTTP+gRPC)
#      - "7881:7881"        # Prometheus metrics
#      - "7882-7980:7882-7980/udp"  # WebRTC
#    restart: unless-stopped

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    environment:
      - LIVEKIT_PROMETHEUS_PORT=7999
      - LIVEKIT_PROMETHEUS_LISTEN=0.0.0.0
    command: --dev
    ports:
      - "7880:7880"
      - "7999:7999"
      - "7882-7980:7882-7980/udp"
    restart: unless-stopped

#  livekit:
#    image: livekit/livekit-server:nightly
#    container_name: livekit
#    environment:
#      - LIVEKIT_PROMETHEUS_PORT=7999
#      - LIVEKIT_PROMETHEUS_LISTEN=0.0.0.0
#    command: --dev
#    ports:
#      - "7880:7880"
#      - "7999:7999"
#      - "7882-7980:7882-7980/udp"
#    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # <- 별도 파일 참조
    ports:
      - "9090:9090"
    depends_on:
      - livekit
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped