port: 7880           # API / Signal 포트 (클라이언트가 붙는 HTTP, gRPC)
rtc:
  tcp_port: 7881     # WebRTC TCP 포트
  udp_port: 7882     # WebRTC UDP 포트
prometheus:
  port: 7999         # Prometheus metrics 포트
# port: 7881         # <- 주석 처리 (여기 쓰면 충돌 가능)