spring:
  docker:
    compose:
      readiness:
        enabled: false
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE         # 메모리 모드 DB (애플리케이션 종료 시 초기화됨)
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true                       # 웹 콘솔 활성화
      path: /h2-console                   # 웹 콘솔 접근 경로 (http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: update                    # 스키마 자동 생성 (create, create-drop, update, validate 등 가능)
    show-sql: true                        # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true

livekit:
  api:
    key: devkey
    secret: this_is_a_very_long_secret_key_for_testing_purposes_12345